# Generated by Django 2.0.4 on 2018-04-20 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dadosaluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('curso', models.CharField(choices=[('Engenharia Civil', 'Engenharia Civil'), ('Engenharia Ambiental e Sanitária', 'Engenharia Ambiental e Sanitária'), ('Engenharia de Petróleo', 'Engenharia de Petróleo'), ('Engenharia Química', 'Engenharia Química')], default=1, max_length=150)),
                ('Número_de_matérias', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caa.dadosaluno')),
            ],
        ),
    ]
