# Generated by Django 2.0.4 on 2018-04-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='Materia',
            field=models.CharField(default=(), max_length=150),
            preserve_default=False,
        ),
    ]
