# Generated by Django 2.0.4 on 2018-04-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0002_materias_materia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materias',
            old_name='Materia',
            new_name='Materia1',
        ),
        migrations.AddField(
            model_name='materias',
            name='Materia2',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
