# Generated by Django 2.0.4 on 2018-04-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0004_cursos_disciplina_respostas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosaluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caa.cursos'),
        ),
    ]
