# Generated by Django 2.0.4 on 2018-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0005_auto_20180421_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosaluno',
            name='curso',
            field=models.CharField(choices=[('Engenharia Civil', 'Engenharia Civil'), ('Engenharia Ambiental e Sanitária', 'Engenharia Ambiental e Sanitária'), ('Engenharia de Petróleo', 'Engenharia de Petróleo'), ('Engenharia Química', 'Engenharia Química')], default=1, max_length=150),
        ),
    ]
