# Generated by Django 2.0.4 on 2018-04-22 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0007_auto_20180421_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='nmaterias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodematerias', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='dadosaluno',
            name='Número_de_matérias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caa.nmaterias'),
        ),
    ]
