# Generated by Django 2.0.4 on 2018-04-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0008_auto_20180422_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='curso',
            new_name='cursos',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='curso',
            new_name='Curso',
        ),
    ]
