# Generated by Django 2.0.4 on 2018-04-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0010_auto_20180422_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='Curso',
            new_name='Cursoo',
        ),
        migrations.RenameField(
            model_name='respostas',
            old_name='Curso',
            new_name='Cursoo',
        ),
    ]
