# Generated by Django 2.0.4 on 2018-04-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0011_auto_20180422_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='disciplinapessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiapessoa', models.CharField(default=1, max_length=150)),
            ],
        ),
    ]
