# Generated by Django 2.0.4 on 2018-04-22 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0012_disciplinapessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='disciplinapessoa',
        ),
    ]
