# Generated by Django 2.0.4 on 2018-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0013_delete_disciplinapessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='dadosaluno',
            name='Número_de_matérias',
        ),
        migrations.AddField(
            model_name='dadosaluno',
            name='materias',
            field=models.ManyToManyField(to='caa.disciplina'),
        ),
        migrations.DeleteModel(
            name='materias',
        ),
        migrations.DeleteModel(
            name='nmaterias',
        ),
    ]
