# Generated by Django 2.0.4 on 2018-04-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0014_auto_20180422_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosaluno',
            name='curso',
        ),
    ]
