# Generated by Django 2.0.4 on 2018-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0015_remove_dadosaluno_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta1',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta10',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta11',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta12',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta13',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta14',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta15',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta16',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta17',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta18',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta2',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta3',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta4',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta5',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta6',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta7',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta8',
        ),
        migrations.RemoveField(
            model_name='respostas',
            name='Resposta9',
        ),
        migrations.AddField(
            model_name='respostas',
            name='Sugestão',
            field=models.CharField(default=0, max_length=900),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta1',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta10',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em parte', 'Em parte')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta11',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta12',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em parte', 'Em parte')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta13',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em parte', 'Em parte')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta14',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta15',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta16',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta17',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta18',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta19',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta2',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta20',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta21',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta22',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em parte', 'Em parte')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta23',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em parte', 'Em parte')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta24',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta25',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta26',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta27',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta28',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta29',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta3',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta30',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta31',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta32',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta33',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta34',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta35',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta4',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta5',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta6',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta7',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta8',
            field=models.CharField(choices=[('Prefiro não opinar', 'Prefiro não opinar'), ('Muito fraco', 'Muito fraco'), ('Fraco', 'Fraco'), ('Regular', 'Regular'), ('Bom', 'Bom'), ('Excelente', 'Excelente')], default='1', max_length=150),
        ),
        migrations.AddField(
            model_name='respostas',
            name='pergunta9',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em parte', 'Em parte')], default='1', max_length=150),
        ),
    ]
