# Generated by Django 2.0.4 on 2018-04-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caa', '0016_auto_20180422_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostas',
            old_name='Cursoo',
            new_name='Curso',
        ),
    ]
